name: 'cloudscale_dbt'
version: '1.0.0'
config-version: 2

profile: 'cloudscale_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  cloudscale_dbt:

    staging:
      +materialized: view
      +schema: silver

    marts:
      +materialized: table
      +schema: gold